"""empty message

Revision ID: 279d4d1e8e37
Revises: fa02cc8e879e
Create Date: 2019-08-07 18:24:42.572166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279d4d1e8e37'
down_revision = 'fa02cc8e879e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gravatar_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gravatar_hash')
    # ### end Alembic commands ###
