"""empty message

Revision ID: 4d69a1be6bdf
Revises: 632e3c3a52c5
Create Date: 2019-07-09 19:02:44.803831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d69a1be6bdf'
down_revision = '632e3c3a52c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rounds', sa.Column('final_snapshot', sa.Text(), nullable=True))
    op.alter_column('rounds', 'result_message',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rounds', 'result_message',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.drop_column('rounds', 'final_snapshot')
    # ### end Alembic commands ###
