"""empty message

Revision ID: 61e3a24f7607
Revises: 0f05a4d247fb
Create Date: 2019-07-26 23:49:53.375253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61e3a24f7607'
down_revision = '0f05a4d247fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('idx', sa.Integer(), nullable=True))
    op.drop_column('games', 'port')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('port', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('games', 'idx')
    # ### end Alembic commands ###
