"""empty message

Revision ID: 632e3c3a52c5
Revises: fc2634511f60
Create Date: 2019-07-09 15:32:19.834447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632e3c3a52c5'
down_revision = 'fc2634511f60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rounds', sa.Column('result_message', sa.String(length=128), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rounds', 'result_message')
    # ### end Alembic commands ###
