"""empty message

Revision ID: c10d21e69e3f
Revises: d61a57c25685
Create Date: 2019-07-07 00:30:59.284436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10d21e69e3f'
down_revision = 'd61a57c25685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('score', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'score')
    # ### end Alembic commands ###
