"""empty message

Revision ID: d7769bdd3462
Revises: 4d69a1be6bdf
Create Date: 2019-07-09 20:52:51.051185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7769bdd3462'
down_revision = '4d69a1be6bdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rounds', sa.Column('result_snapshot', sa.Text(), nullable=True))
    op.drop_column('rounds', 'final_snapshot')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rounds', sa.Column('final_snapshot', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('rounds', 'result_snapshot')
    # ### end Alembic commands ###
