"""empty message

Revision ID: fa02cc8e879e
Revises: 61e3a24f7607
Create Date: 2019-07-30 19:30:07.317501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa02cc8e879e'
down_revision = '61e3a24f7607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
