"""empty message

Revision ID: fc2634511f60
Revises: 2ccedde13096
Create Date: 2019-07-07 19:36:21.550146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc2634511f60'
down_revision = '2ccedde13096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friendlyname', sa.String(length=64), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_friendlyname'), 'games', ['friendlyname'], unique=True)
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.Column('game_friendlyname', sa.String(length=64), nullable=False),
    sa.Column('user_username', sa.String(length=64), nullable=True),
    sa.Column('score', sa.Integer(), server_default='0', nullable=True),
    sa.ForeignKeyConstraint(['game_friendlyname'], ['games.friendlyname'], ),
    sa.ForeignKeyConstraint(['user_username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rounds')
    op.drop_index(op.f('ix_games_friendlyname'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
